version: '3'
services:
        web:
                build: .
                ports:
                        - "5678:5678"  
                depends_on:
                        - "db"
        db:
                image: "mongo"
